# Generated by Django 6.0.3 on 2026-04-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('opciones', models.JSONField(default=list)),
                ('respuesta_correcta', models.CharField(max_length=200)),
                ('explicacion', models.TextField(blank=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_ejercicio', models.CharField(choices=[('multiple', 'Opción múltiple'), ('completar', 'Completar'), ('verdadero_falso', 'Verdadero/Falso')], default='multiple', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
