# Generated by Django 4.2.30 on 2026-04-29 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_nino_tarea_ninos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgresoTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada', models.BooleanField(default=False)),
                ('puntos_obtenidos', models.IntegerField(default=0)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_tareas', to='tareas.nino')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.tarea')),
            ],
            options={
                'unique_together': {('nino', 'tarea')},
            },
        ),
    ]
