# Generated by Django 4.2.30 on 2026-04-29 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_progresotarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioProgreso',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('skill_id', models.IntegerField(blank=True, null=True)),
                ('difficulty', models.IntegerField(blank=True, null=True)),
                ('time_spent_ms', models.IntegerField(default=0)),
                ('attempts', models.IntegerField(default=1)),
                ('used_hint', models.BooleanField(default=False)),
                ('n_hints', models.IntegerField(default=0)),
                ('fast_response', models.BooleanField(default=False)),
                ('correct', models.BooleanField(default=False)),
                ('tab_blur_count', models.IntegerField(default=0)),
                ('idle_ms', models.IntegerField(default=0)),
                ('erratic_clicks', models.IntegerField(default=0)),
                ('error_type', models.CharField(blank=True, max_length=100)),
                ('will_mistake_next', models.BooleanField(default=False)),
                ('focus_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tareas_progreso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(default='star', max_length=50)),
                ('rareza', models.CharField(choices=[('bronce', 'Bronce'), ('plata', 'Plata'), ('oro', 'Oro'), ('legendario', 'Legendario')], default='bronce', max_length=20)),
                ('condicion', models.CharField(choices=[('tareas_completadas', 'Tareas Completadas'), ('tareas_perfectas', 'Tareas Sin Errores'), ('racha_dias', 'Racha de Días'), ('respuestas_rapidas', 'Respuestas Rápidas'), ('nivel_alcanzado', 'Nivel Alcanzado'), ('monedas_acumuladas', 'Monedas Acumuladas')], max_length=50)),
                ('valor_requerido', models.IntegerField()),
                ('puntos_bonus', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LogroNino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desbloqueado', models.DateTimeField(auto_now_add=True)),
                ('logro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.logro')),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logros_desbloqueados', to='tareas.nino')),
            ],
            options={
                'unique_together': {('nino', 'logro')},
            },
        ),
    ]
