# Generated by Django 4.2.30 on 2026-05-06 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_ejercicioprogreso_logro_logronino'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresotarea',
            name='cantidad_aciertos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progresotarea',
            name='cantidad_errores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progresotarea',
            name='tiempo_total_ms',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProgresoPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completada', models.BooleanField(default=True)),
                ('puntos_obtenidos', models.IntegerField(default=0)),
                ('cantidad_aciertos', models.IntegerField(default=0)),
                ('cantidad_errores', models.IntegerField(default=0)),
                ('tiempo_total_ms', models.IntegerField(default=0)),
                ('dificultad', models.IntegerField(default=1)),
                ('tipo_ejercicio', models.CharField(choices=[('multiple', 'Opción múltiple'), ('completar', 'Completar'), ('verdadero_falso', 'Verdadero/Falso')], default='multiple', max_length=50)),
                ('fecha_practica', models.DateTimeField(auto_now_add=True)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progreso_practicas', to='tareas.nino')),
            ],
            options={
                'db_table': 'tarea_progresopractica',
            },
        ),
    ]
