# Generated by Django 4.2.30 on 2026-05-06 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0006_progresotarea_campos_nuevos_progresopractica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresotarea',
            name='cantidad_aciertos',
        ),
        migrations.RemoveField(
            model_name='progresotarea',
            name='cantidad_errores',
        ),
        migrations.RemoveField(
            model_name='progresotarea',
            name='tiempo_total_ms',
        ),
        migrations.AlterField(
            model_name='progresopractica',
            name='completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='progresopractica',
            name='nino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_practica', to='tareas.nino'),
        ),
        migrations.AlterField(
            model_name='progresopractica',
            name='tipo_ejercicio',
            field=models.CharField(choices=[('multiple', 'Opción múltiple'), ('completar', 'Completar'), ('verdadero_falso', 'Verdadero/Falso'), ('practica_libre', 'Práctica Libre')], default='practica_libre', max_length=50),
        ),
        migrations.AlterModelTable(
            name='progresopractica',
            table=None,
        ),
    ]
