# Generated by Django 4.2.30 on 2026-05-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0007_remove_progresotarea_cantidad_aciertos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('opciones', models.JSONField(default=list)),
                ('respuesta_correcta', models.CharField(max_length=200)),
                ('tipo_ejercicio', models.CharField(choices=[('multiple', 'Opción múltiple'), ('completar', 'Completar'), ('verdadero_falso', 'Verdadero/Falso')], default='multiple', max_length=50)),
                ('categoria', models.CharField(choices=[('matematicas', 'Matemáticas'), ('lengua', 'Lengua'), ('ciencias', 'Ciencias'), ('ingles', 'Inglés')], default='matematicas', max_length=50)),
                ('dificultad', models.IntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
