# Generated by Django 4.2.30 on 2026-05-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0008_ejerciciopractica'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresotarea',
            name='cantidad_aciertos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progresotarea',
            name='cantidad_errores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progresotarea',
            name='tiempo_total_ms',
            field=models.IntegerField(default=0),
        ),
    ]
