# Generated by Django 4.2.30 on 2026-05-20 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0009_progresotarea_cantidad_aciertos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.CharField(max_length=200)),
                ('avatar_key', models.CharField(max_length=50, unique=True)),
                ('precio', models.IntegerField(default=0)),
                ('rareza', models.CharField(choices=[('comun', 'Común'), ('raro', 'Raro'), ('legendario', 'Legendario')], default='comun', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.CharField(max_length=200)),
                ('precio', models.IntegerField(default=0)),
                ('rareza', models.CharField(choices=[('comun', 'Común'), ('raro', 'Raro'), ('legendario', 'Legendario')], default='comun', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StickerComprado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers_comprados', to='tareas.nino')),
                ('sticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.sticker')),
            ],
            options={
                'unique_together': {('nino', 'sticker')},
            },
        ),
        migrations.CreateModel(
            name='SkinComprada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skins_compradas', to='tareas.nino')),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.skin')),
            ],
            options={
                'unique_together': {('nino', 'skin')},
            },
        ),
    ]
