# Generated by Django 4.2.30 on 2026-06-02 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0010_skin_sticker_stickercomprado_skincomprada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logro',
            name='condicion',
            field=models.CharField(choices=[('tareas_completadas', 'Tareas Completadas'), ('tareas_perfectas', 'Tareas Sin Errores'), ('racha_dias', 'Racha de Días'), ('respuestas_rapidas', 'Respuestas Rápidas'), ('nivel_alcanzado', 'Nivel Alcanzado'), ('monedas_acumuladas', 'Monedas Acumuladas'), ('practicas_completadas', 'Prácticas Completadas'), ('experiencia_total', 'Experiencia Total')], max_length=50),
        ),
        migrations.CreateModel(
            name='PrediccionError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_error', models.CharField(choices=[('fracciones', 'Fracciones'), ('multiplicacion', 'Multiplicación'), ('division', 'División'), ('algebra', 'Álgebra'), ('geometria', 'Geometría'), ('procedimiento', 'Procedimiento'), ('conceptual', 'Conceptual'), ('inatencion', 'Inatencion'), ('consigna', 'Consigna'), ('aleatorio', 'Aleatorio')], max_length=50)),
                ('probabilidad', models.FloatField()),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True)),
                ('notificado', models.BooleanField(default=False)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones', to='tareas.nino')),
            ],
        ),
        migrations.CreateModel(
            name='EventoDistraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_score', models.FloatField()),
                ('tab_blur_count', models.IntegerField()),
                ('idle_ms', models.IntegerField()),
                ('erratic_clicks', models.IntegerField()),
                ('fecha_evento', models.DateTimeField(auto_now_add=True)),
                ('descanso_mostrado', models.BooleanField(default=False)),
                ('nino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_distraccion', to='tareas.nino')),
            ],
        ),
    ]
